piplus_piplus:
  cuts:
    - "Mh>0.9"
    - "Mh<1.1"
piplus_pi0:
  cuts:
    - "Mh>0.9"
    - "Mh<1.1"
piplus_piminus:
  cuts:
    - "Mh>0.9"
    - "Mh<1.1"
piminus_piminus:
  cuts:
    - "Mh>0.9"
    - "Mh<1.1"
piminus_pi0:
  cuts:
    - "Mh>0.9"
    - "Mh<1.1"
pi0_pi0:
  cuts:
    - "Mh>0.9"
    - "Mh<1.1"