piplus_piplus:
  cuts:
    - "Mh>0.6"
    - "Mh<0.9"
piplus_pi0:
  cuts:
    - "Mh>0.6"
    - "Mh<0.9"
piplus_piminus:
  cuts:
    - "Mh>0.6"
    - "Mh<0.9"
piminus_piminus:
  cuts:
    - "Mh>0.6"
    - "Mh<0.9"
piminus_pi0:
  cuts:
    - "Mh>0.6"
    - "Mh<0.9"
pi0_pi0:
  cuts:
    - "Mh>0.6"
    - "Mh<0.9"