bin_variable: "Mh"
piplus_piplus:
  cuts:
    - "Mh>0.6"
    - "Mh<0.8"
piplus_pi0:
  cuts:
    - "Mh>0.6"
    - "Mh<0.8"
piplus_piminus:
  cuts:
    - "Mh>0.6"
    - "Mh<0.8"
piminus_piminus:
  cuts:
    - "Mh>0.6"
    - "Mh<0.8"
piminus_pi0:
  cuts:
    - "Mh>0.6"
    - "Mh<0.8"
pi0_pi0:
  cuts:
    - "Mh>0.6"
    - "Mh<0.8"