piplus_piplus:
  cuts:
    - "Mh>1.0"
    - "Mh<1.2"
piplus_pi0:
  cuts:
    - "Mh>1.0"
    - "Mh<1.2"
piplus_piminus:
  cuts:
    - "Mh>1.0"
    - "Mh<1.2"
piminus_piminus:
  cuts:
    - "Mh>1.0"
    - "Mh<1.2"
piminus_pi0:
  cuts:
    - "Mh>1.0"
    - "Mh<1.2"
pi0_pi0:
  cuts:
    - "Mh>1.0"
    - "Mh<1.2"