bin_variable: "Mh"
piplus_piplus:
  cuts:
    - "Mh>0.0"
    - "Mh<0.6"
piplus_pi0:
  cuts:
    - "Mh>0.0"
    - "Mh<0.6"
piplus_piminus:
  cuts:
    - "Mh>0.0"
    - "Mh<0.6"
piminus_piminus:
  cuts:
    - "Mh>0.0"
    - "Mh<0.6"
piminus_pi0:
  cuts:
    - "Mh>0.0"
    - "Mh<0.6"
pi0_pi0:
  cuts:
    - "Mh>0.0"
    - "Mh<0.6"