bin_variable: "Mh"
piplus_piplus:
  cuts:
    - "Mh>0.8"
    - "Mh<1.0"
piplus_pi0:
  cuts:
    - "Mh>0.8"
    - "Mh<1.0"
piplus_piminus:
  cuts:
    - "Mh>0.8"
    - "Mh<1.0"
piminus_piminus:
  cuts:
    - "Mh>0.8"
    - "Mh<1.0"
piminus_pi0:
  cuts:
    - "Mh>0.8"
    - "Mh<1.0"
pi0_pi0:
  cuts:
    - "Mh>0.8"
    - "Mh<1.0"