bin_variable: "Mh"
piplus_piplus:
  cuts:
    - "Mh>1.0"
    - "Mh<2.5"
piplus_pi0:
  cuts:
    - "Mh>1.0"
    - "Mh<2.5"
piplus_piminus:
  cuts:
    - "Mh>1.0"
    - "Mh<2.5"
piminus_piminus:
  cuts:
    - "Mh>1.0"
    - "Mh<2.5"
piminus_pi0:
  cuts:
    - "Mh>1.0"
    - "Mh<2.5"
pi0_pi0:
  cuts:
    - "Mh>1.0"
    - "Mh<2.5"